<div class="page-header">
    <h1>Modulo Catalogos y reportes</h1>
</div>

<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Catalogos</h3>
        </div>
        <div class="panel-body">
            <a class="btn btn-primary btn-block" href="/modulo1/catalogo/alluser">Usuarios</a>
            <a class="btn btn-primary btn-block" href="/modulo1/catalogo/allproveedor">Proveedores</a>
            <a class="btn btn-primary btn-block" href="/modulo1/catalogo/allproducto">Productos</a>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Reportes</h3>
        </div>
        <div class="panel-body">
            <a class="btn btn-primary btn-block" href="/modulo1/reporte/prodescasos">Productos escasos</a>
            <a class="btn btn-primary btn-block" href="/modulo1/reporte/vendidos">Productos vendidos</a>
            <a class="btn btn-primary btn-block" href="/modulo1/reporte/surtidos">Surtido productos</a>
            <a class="btn btn-primary btn-block" href="/modulo1/reporte/bitacora">Bitacora</a>
        </div>
    </div>
</div>