<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \Application\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id_producto', 'descripcion', 'marca', 'punto_reorden', 'id_grupo', 'finito', 'ufecha');
        }

        return array('__isInitialized__', 'id_producto', 'descripcion', 'marca', 'punto_reorden', 'id_grupo', 'finito', 'ufecha');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Producto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($param)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($param));

        return parent::setDescripcion($param);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarca', array());

        return parent::getMarca();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarca($param)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarca', array($param));

        return parent::setMarca($param);
    }

    /**
     * {@inheritDoc}
     */
    public function getPunto_reorden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPunto_reorden', array());

        return parent::getPunto_reorden();
    }

    /**
     * {@inheritDoc}
     */
    public function setPunto_reorden($param)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPunto_reorden', array($param));

        return parent::setPunto_reorden($param);
    }

    /**
     * {@inheritDoc}
     */
    public function getId_grupo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId_grupo', array());

        return parent::getId_grupo();
    }

    /**
     * {@inheritDoc}
     */
    public function setId_grupo($param)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId_grupo', array($param));

        return parent::setId_grupo($param);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinito', array());

        return parent::getFinito();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinito($param)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinito', array($param));

        return parent::setFinito($param);
    }

    /**
     * {@inheritDoc}
     */
    public function getUfecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUfecha', array());

        return parent::getUfecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setUfecha($param)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUfecha', array($param));

        return parent::setUfecha($param);
    }

}
