<div class="page-header">
    <h1>Modulo Almacenista</h1>
</div>
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Almacen</h3>
        </div>
        <div class="panel-body">
            <a class="btn btn-primary btn-block" href="/modulo2/surtimiento/allsurtimiento">Surtimiento</a>
            <a class="btn btn-primary btn-block" href="/modulo2/compra/allcompra">Compra</a>
            <a class="btn btn-primary btn-block" href="/modulo2/surtimiento/addexistencia">Existencia</a>
        </div>
    </div>
</div>