<form method="post" id="miform">
    <div class="form-group">
        <label for="idproducto">Producto</label>
        <select name="idproducto" form="miform" class="form-control" id="idproducto">
            <?php
            foreach ($productos as $p) {
                //$p=new Application\Entity\Producto;
                echo '<option value="' . $p->getId() . '">' . $p->getDescripcion() . '</option>';
            }
            ?>
        </select>
    </div>
    <div class="form-group">
        <label for="idusuario">Usuario</label>
        <select name="idusuario" form="miform" class="form-control" id="idusuario">
            <?php
            foreach ($usuarios as $u) {
                //$u=new Application\Entity\Usuario;
                echo '<option value="' . $u->getId() . '">' . $u->getNombre() . '</option>';
            }
            ?>
        </select>
    </div>
    <div class="form-group">
        <label for="cuanto">Cuanto</label>
        <input name="cuanto" type="number" required="" class="form-control" id="cuanto" placeholder="Cuanto">
    </div>
    <div class="form-group">
        <label for="precio">Precio</label>
        <input name="precio" type="number" required="" class="form-control" id="precio" placeholder="Precio">
    </div>
    <button class="btn btn-info" type="submit">Guardar</button>
</form>