<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
?>
<h1>
    Listado de productos mas vendidos
</h1>
<table class="table table-bordered table-condensed table-hover table-responsive">
    <thead>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($productos as $p) {
            ?>
            <tr>
                <td><?php echo $p[0]; ?></td>
                <td><?php echo $p[1]; ?></td>
            <tr>
                <?php
            }
            ?>
    </tbody>
</table>
<a href="/modulo1" class="btn btn-info right">Regresar</a>