<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
?>
<form method="post">
    <div class="form-group">
        <label for="descripcion">Descripcion</label>
        <input name="descripcion" type="text" class="form-control" id="descripcion" placeholder="Descripcion">
    </div>
    <div class="form-group">
        <label for="finito">Finito</label>
        <input name="finito" type="text" class="form-control" id="finito" placeholder="Finito">
    </div>
    <div class="form-group">
        <label for="grupo">Grupo</label>
        <input name="grupo" type="number" class="form-control" id="grupo" placeholder="Grupo">
    </div>
    <div class="form-group">
        <label for="marca">Marca</label>
        <input name="marca" type="text" class="form-control" id="marca" placeholder="Marca">
    </div>
    <div class="form-group">
        <label for="reorden">Reorden</label>
        <input name="reorden" type="text" class="form-control" id="reorden" placeholder="Reorden">
    </div>
    
    <button type="submit" class="btn btn-success btn-lg">Guardar</button>
</form>
<a class="btn btn-info" href="/modulo1/catalogo/allproducto">Regresar</a>