<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
?>
<form method="post">
    <div class="form-group">
        <label for="nombre">Nombre</label>
        <input name="nombre" type="text" class="form-control" id="nombre" placeholder="Nombre">
    </div>
    <div class="form-group">
        <label for="direccion">Direccion</label>
        <input name="direccion" type="text" class="form-control" id="direccion" placeholder="Direccion">
    </div>
    <div class="form-group">
        <label for="rfc">Rfc</label>
        <input name="rfc" type="text" class="form-control" id="rfc" placeholder="Grupo">
    </div>
    <div class="form-group">
        <label for="telefono">Telefono</label>
        <input name="telefono" type="text" class="form-control" id="telefono" placeholder="Telefono">
    </div>
    
    <button type="submit" class="btn btn-success btn-lg">Guardar</button>
</form>
<a class="btn btn-info" href="/modulo1/catalogo/allproveedor">Regresar</a>