<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
?>
<h1>
    Listado de productos
    <a href="/modulo1/catalogo/addproducto" class="btn btn-success">Nuevo</a>
</h1>
<table class="table table-bordered table-condensed table-hover table-responsive">
    <thead>
        <tr>
            <th>Descripcion</th>
            <th>Marca</th>
            <th>Grupo</th>
            <th>Cantidad</th>
            <th>Fecha</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($productos as $p) {
            $timestamp = $p->getUfecha();
            $timestamp= json_encode($timestamp);
            $timestamp= json_decode($timestamp);
            ?>
            <tr>
                <td><?php echo $p->getDescripcion(); ?></td>
                <td><?php echo $p->getMarca(); ?></td>
                <td><?php echo $p->getId_grupo(); ?></td>
                <td><?php echo $p->getFinito(); ?></td>
                <td><?php echo $timestamp->date; ?></td>
                <td><a href="/modulo1/catalogo/editproducto/<?php echo $p->getId(); ?>" class="btn btn-warning btn-sm">Editar</a><a href="/modulo1/catalogo/deleteproducto/<?php echo $p->getId();  ?>" class="btn btn-danger btn-sm">Eliminar</a></td>
            <tr>
                <?php
            }
            ?>
    </tbody>
</table>
<a href="/modulo1" class="btn btn-info right">Regresar</a>