<h1>
    Listado de provedores
    <a href="/modulo1/catalogo/addproveedor" class="btn btn-success">Nuevo</a>
</h1>
<table class="table table-bordered table-condensed table-hover table-responsive">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Rfc</th>
            <th>Telefono</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($proveedores as $p) {
            ?>
            <tr>
                <td><?php echo $p->getNombre(); ?></td>
                <td><?php echo $p->getDireccion(); ?></td>
                <td><?php echo $p->getRfc(); ?></td>
                <td><?php echo $p->getTelefono(); ?></td>
                <td><a href="/modulo1/catalogo/editproveedor/<?php echo $p->getId(); ?>" class="btn btn-warning btn-sm">Editar</a><a href="/modulo1/catalogo/deleteproveedor/<?php echo $p->getId();  ?>" class="btn btn-danger btn-sm">Eliminar</a></td>
            <tr>
                <?php
            }
            ?>
    </tbody>
</table>
<a href="/modulo1" class="btn btn-info right">Regresar</a>