<h1>
    Listado de usuarios
    <a href="/modulo1/catalogo/adduser" class="btn btn-success">Nuevo</a>
</h1>
<table class="table table-bordered table-condensed table-hover table-responsive">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Password</th>
            <th>Nivel</th>
            <th>Activo</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($usuarios as $u) {
            ?>
            <tr>
                <td><?php echo $u->getNombre(); ?></td>
                <td><?php echo $u->getPwd(); ?></td>
                <td><?php echo $u->getNivel(); ?></td>
                <td><?php echo $u->getActivo(); ?></td>
                <td><a href="/modulo1/catalogo/edituser/<?php echo $u->getId(); ?>" class="btn btn-warning btn-sm">Editar</a><a href="/modulo1/catalogo/deleteuser/<?php echo $u->getId();  ?>" class="btn btn-danger btn-sm">Eliminar</a></td>
            <tr>
                <?php
            }
            ?>
    </tbody>
</table>
<a href="/modulo1" class="btn btn-info right">Regresar</a>