<form method="post">
    <div class="form-group">
        <label for="nombre">Nombre</label>
        <input value="<?php echo $usuario->getNombre(); ?>" name="nombre" type="text" class="form-control" id="nombre" placeholder="Nombre">
    </div>
    <div class="form-group">
        <label for="pwd">Contraseña</label>
        <input value="<?php echo $usuario->getPwd(); ?>" name="pwd" type="password" class="form-control" id="pwd" placeholder="Contraseña">
    </div>
    <div class="form-group">
        <label for="nivel">Nivel</label>
        <select  name="nivel" id="nivel" class="form-control">
            <option value="Administrador">Administrador</option>
            <option value="Gerente">Gerente</option>
            <option value="Vendedor">Vendedor</option>
            <option value="Supervisor">Supervisor</option>
            <option value="Comprador">Comprador</option>
            <option value="Surtidor">Surtidor</option>
        </select>
    </div>
    <div class="form-group">
        <label for="activo">Activo</label>
        <select name="activo">
            <option value="1" selected="">Si</option>
            <option value="0">No</option>
        </select>
    </div>
    <button type="submit" class="btn btn-success btn-lg">Guardar</button>
</form>
<a href="/modulo1/catalogo/alluser">Regresar</a>