<div class="page-header">
    <h1>Modulo Vendedor</h1>
</div>
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Vendedor</h3>
        </div>
        <div class="panel-body">
            <a class="btn btn-primary btn-block" href="/modulo3/ventas/alldesgloce">Desgloce</a>
            <a class="btn btn-primary btn-block" href="/modulo3/ventas/allventa">Venta</a>
            <a class="btn btn-primary btn-block" href="/modulo3/cortes/allcorte">Corte</a>
        </div>
    </div>
</div>