<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
?>

<h1>
    Listado de desgloces
    <a href="/modulo3/ventas/addventa" class="btn btn-success">Nuevo</a>
</h1>
<table class="table table-bordered table-condensed table-hover table-responsive">
    <thead>
        <tr>
            <th>Total</th>
            <th>Efectivo</th>
            <th>Redondero</th>
            <th>Cambio</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($ventas as $v) {
            ?>
            <tr>
                <td><?php echo $v->getTotal(); ?></td>
                <td><?php echo $v->getEfectivo(); ?></td>
                <td><?php echo $v->getRedondeo(); ?></td>
                <td><?php echo $v->getCambio(); ?></td>
            <tr>
                <?php
            }
            ?>
    </tbody>
</table>
<a href="/modulo3" class="btn btn-info right">Regresar</a>