<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
?>
<figure>
    <td><img src="http://www.sistema.ittg.mx/img/logo.jpg" align="left"></td>
</figure>
<h1>Bienvenido a la plataforma TiendaDescartes</h1>
<h3>Favor de pasar a la seccion de <a href="<?php echo $this->basePath() ?>/users/register">Login</a></h3>
<!--div class="row">
    <form method="post" class="form-signin col-md-4 col-md-offset-4">
        <h2 class="form-signin-heading">Iniciar sesion</h2>
        <label for="nombre" class="sr-only">Usuario</label>
        <input name="nombre" id="nombre" class="form-control" placeholder="Usuario" required="" autofocus="" type="text">
        <label for="pwd" class="sr-only">Contraseña</label>
        <input name="pwd" id="pwd" class="form-control" placeholder="Contraseña" required="" type="password">
        
        <button class="btn btn-lg btn-primary btn-block" type="submit">Iniciar</button>
        
    </form>
</div-->
